### ISSUE TITLE
Failed to play on ZEPETO mobile app

### ISSUE THREAD

**Issue by NineWoranop** [naverz/zepeto-world-sample#1]
Hi,

I'm a beginner that try to create a world on ZEPETO. I followed the guide on [this link](https://studio.zepeto.me/guides/installing-unity-and-registering-zepeto-template) by installed Unity version 2020.3.9f1 and installed plugin by use ZEPETO World template. Everything went well until I created new ZEPETO default project.
The scene could play on Unity and the cube at the center of the screen is rotating properly. When I try to play on mobile via ZEPETO menu, it pop up for QR code but I try to login via QR Code. I always got "Error accessing ZEPETO World Please try again" error. 
![Failed_load_on_mobile](https://user-images.githubusercontent.com/9558241/187463946-60acf106-4399-4e8e-849b-6d225809c929.jpg)
I try to open this sample project, it don't show any errors but it don't show any QR Code popup.
I'm not sure that error come from plugin or example so I decide to post my error here.
Could you please give me any suggestions how to run this sample?

**Comment by Zepeto-TechEvangelist** [comment]
The QR code test works only when the smartphone and the development PC are connected to the same network environment.
If the connection is not smooth on your Windows PC, check by changing the firewall settings.
Also, if the network is set to a public network instead of a private one on a Windows PC, world access is not possible due to security issues.
Make sure that 'Personal' is selected in Network and Internet Settings > Properties.
 
![ip_edited (1)](https://user-images.githubusercontent.com/100118650/195259466-16c724a1-e4d8-4f85-92ba-3830038986cd.png)

You can check which network environment you are connected to in the lower right part of the QR pop-up window, and click to change the network environment.
